### ISSUE TITLE
Azure support

### ISSUE THREAD

**Issue by svopex** [fluentscheduler/FluentScheduler#80] opened 2016-05-16 08:46 UTC
Hello,

I use in Azure:
`
Schedule<EpoSchedulerDoCleanNumberOfUnsuccessfulActivations>().ToRunEvery(1).Days().At(1, 0);
`

On the weekend this task go to sleep, fluentscheduler call Execute() only first day (friday).

Petr

**Comment by tallesl** [comment] 2016-05-17 17:08
Hi,

Do you know if this happens only in Azure? (Have you tested it somewhere?)

**Comment by svopex** [comment] 2016-05-17 18:12
Yes, FluentScheduler don't work only in windows azure.

**Comment by tallesl** [comment] 2016-05-18 21:26
I'm not gonna lie to you, it's somewhat hard to me to reproduce your issue (I don't have an azure box and I'm not used to set it up).

Have you considered that maybe your box is sleeping on weekends?

Since this happens only in azure (and not when running on your own) I would assume that is something in your azure configuration (but that's an assumption, could be FluentScheduler fault somehow).

**Comment by svopex** [comment] 2016-05-19 07:52
No, web page don't slept on the weekend.
We use alive mode.
I test quartz now [http://www.quartz-scheduler.net/](url) and I report here, if quartz work or not at weekend.

**Comment by svopex** [comment] 2016-05-23 06:25
Hello, quartz work without any problem and FluentScheduler not.
We use this settings of web in azure:
[http://www.ftp.svopex.com/temp/fluentscheduler/azure_settings.png](url)

**Comment by americanslon** [comment] 2017-10-05 18:13
Has there been any new developments on this?
I have a super simple job definition that doesn't even run once on 

registry.Schedule<Trade>().ToRunEvery(5).Minutes();

No errors either (or i can't find them) just doesn't get triggered on Azure.

**Comment by svopex** [comment] 2017-10-05 19:16
Hello, I have used Quartz. fluentscheduler not work on the Azure.

**Comment by EngelenH** [comment] 2017-10-23 12:11
https://blogs.msdn.microsoft.com/dotnet/2017/10/19/experiment-with-azure-for-free/?utm_source=vs_developer_news&utm_medium=referral

Should you want to experiment with azure this might be a worthwhile read

**Comment by pkmccaffrey** [comment] 2017-11-01 16:14
@tallesl - For the record, I'm using Fluent Scheduler in an Azure environment.  My jobs run at various intervals (from every hour, to once per month), and I haven't seen any issues.

**Comment by americanslon** [comment] 2017-11-01 16:15
@pkmccaffrey APP service or a VM?

**Comment by pkmccaffrey** [comment] 2018-01-31 17:20
@americanslon - Sorry, didn't see this until now.  That site is running as an app service.

**Comment by tallesl** [comment] 2018-08-26 22:38
I'm closing the issue, but feel free to ask to reopen it.

**Closed by tallesl** 2018-08-26 22:38 UTC
Labels: help wanted
